{{ if eq .Values.ahoy.clusterType "kubernetes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ template "ahoy.name" . }}
  name: {{ template "ahoy.server.fullname" . }}
spec:
  {{ if .Values.ahoy.tlsSecret }}
  tls:
    - secretName: {{ .Values.ahoy.tlsSecret }}
  {{ end }}
  rules:
    - host: {{ .Values.ahoy.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "ahoy.server.fullname" . }}
                port:
                  number: 8080
  {{ end }}
