{{ if eq .Values.ahoy.clusterType "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "ahoy.name" . }}
  name: {{ template "ahoy.server.fullname" . }}
spec:
  host: {{ .Values.ahoy.host }}
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ template "ahoy.server.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
  {{ end }}
