name: Chart Publish

on:
  push:
    branches:
      - main

jobs:
  publish-chart:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Publish Helm charts
          uses: stefanprodan/helm-gh-pages@v1.5.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
